### ISSUE TITLE
Grouping tiles from different `<juicy-tile-list>`s should be blocked

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/Launcher#85]

**Comment by miyconst** [comment]
Why it should be blocked? Is this issue still relevant, by the way?

**Comment by warpech** [comment]
Because each `juicy-tile-list` hosts the setup JSON for it's child elements. If you move a tile to another `juicy-tile-list`, then you have a cross-list behavior in which `juicy-tile-list#1` holds the setup for a child element of `juicy-tile-list#2`.

It is wrong for 2 reasons:

1. now you would need to synchronize setups between 2 `juicy-tile-lists` (so that the element does not get distributed twice)
2. both `juicy-tile-list` would be hard dependent on each other. What in a case when one of them is not loaded?

**Comment by miyconst** [comment]
Well.. this would limit me as a layout designer very much. I very often combine in a group elements from different apps. Am I missing something?

**Comment by warpech** [comment]
I will use the example of People app to explain how I understand the problem: 

Currently, the editor does not prevent me from selecting two divs that belong to separate `juicy-tile-list`s (a div that is inside `EmailAddressPage.html`and a div that is inside `PhoneNumberPage.html`) and group them together:

<img width="1401" alt="screenshot 2015-09-16 14 51 46" src="https://cloud.githubusercontent.com/assets/566463/9905044/b7fdd09a-5c82-11e5-9b55-4b7a33728510.png">

However, it gives a quite unintended result:

<img width="1403" alt="screenshot 2015-09-16 14 52 06" src="https://cloud.githubusercontent.com/assets/566463/9905070/d9b27344-5c82-11e5-80b9-f3a4a596bff4.png">


Do you have another idea how to solve it?

**Comment by miyconst** [comment]
I have solved this issue while migrating to Polymer 1.1, `juicy-tile-editor` alerts a message, that tiles from different `juicy-tile-list` could not be grouped. I should double check that it works with multiply selected items. Assigning this on me.
